// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ClickhouseClusterRequestInputBackupOptionsSettings struct {
	Day    int64  `json:"day"`
	Keep   int64  `json:"keep"`
	Period string `json:"period"`
	Time   string `json:"time"`
}

type ClickhouseClusterRequestInputBackupOptions struct {
	Arn               string                                               `json:"arn"`
	Bucket            string                                               `json:"bucket"`
	CompressionFormat string                                               `json:"compressionFormat"`
	Day               int64                                                `json:"day"`
	Enable            bool                                                 `json:"enable"`
	Path              string                                               `json:"path"`
	Provider          string                                               `json:"provider"`
	Region            string                                               `json:"region"`
	Schedule          string                                               `json:"schedule"`
	SecretKey         string                                               `json:"secretKey"`
	Settings          []ClickhouseClusterRequestInputBackupOptionsSettings `json:"settings"`
	Time              string                                               `json:"time"`
}

type ClickhouseClusterRequestInputDatadogSettings struct {
	Logs    bool `json:"logs"`
	Metrics bool `json:"metrics"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleFriRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleFri struct {
	Active bool                                                        `json:"active"`
	AllDay bool                                                        `json:"allDay"`
	Range  ClickhouseClusterRequestInputUptimeSettingsScheduleFriRange `json:"range"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleMonRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleMon struct {
	Active bool                                                        `json:"active"`
	AllDay bool                                                        `json:"allDay"`
	Range  ClickhouseClusterRequestInputUptimeSettingsScheduleMonRange `json:"range"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleSatRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleSat struct {
	Active bool                                                        `json:"active"`
	AllDay bool                                                        `json:"allDay"`
	Range  ClickhouseClusterRequestInputUptimeSettingsScheduleSatRange `json:"range"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleSunRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleSun struct {
	Active bool                                                        `json:"active"`
	AllDay bool                                                        `json:"allDay"`
	Range  ClickhouseClusterRequestInputUptimeSettingsScheduleSunRange `json:"range"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleThuRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleThu struct {
	Active bool                                                        `json:"active"`
	AllDay bool                                                        `json:"allDay"`
	Range  ClickhouseClusterRequestInputUptimeSettingsScheduleThuRange `json:"range"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleTueRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleTue struct {
	Active bool                                                        `json:"active"`
	AllDay bool                                                        `json:"allDay"`
	Range  ClickhouseClusterRequestInputUptimeSettingsScheduleTueRange `json:"range"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleWedRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterRequestInputUptimeSettingsScheduleWed struct {
	Active bool                                                        `json:"active"`
	AllDay bool                                                        `json:"allDay"`
	Range  ClickhouseClusterRequestInputUptimeSettingsScheduleWedRange `json:"range"`
}

type ClickhouseClusterRequestInputUptimeSettingsSchedule struct {
	Fri ClickhouseClusterRequestInputUptimeSettingsScheduleFri `json:"fri"`
	Mon ClickhouseClusterRequestInputUptimeSettingsScheduleMon `json:"mon"`
	Sat ClickhouseClusterRequestInputUptimeSettingsScheduleSat `json:"sat"`
	Sun ClickhouseClusterRequestInputUptimeSettingsScheduleSun `json:"sun"`
	Thu ClickhouseClusterRequestInputUptimeSettingsScheduleThu `json:"thu"`
	Tue ClickhouseClusterRequestInputUptimeSettingsScheduleTue `json:"tue"`
	Wed ClickhouseClusterRequestInputUptimeSettingsScheduleWed `json:"wed"`
}

type ClickhouseClusterRequestInputUptimeSettings struct {
	InactiveHours int64                                               `json:"inactiveHours"`
	Schedule      ClickhouseClusterRequestInputUptimeSettingsSchedule `json:"schedule"`
}

type ClickhouseClusterRequestInputZookeeperOptions struct {
	Root string  `json:"root"`
	Size string  `json:"size"`
	Tag  *string `json:"tag,omitempty"`
}

type ClickhouseClusterRequestInput struct {
	AdminPass          string                                        `json:"adminPass"`
	AdminUser          string                                        `json:"adminUser"`
	AlternateEndpoints []interface{}                                 `json:"alternateEndpoints,omitempty"`
	Azlist             []string                                      `json:"azlist"`
	BackupOptions      ClickhouseClusterRequestInputBackupOptions    `json:"backupOptions"`
	DatadogSettings    ClickhouseClusterRequestInputDatadogSettings  `json:"datadogSettings"`
	Disks              int64                                         `json:"disks"`
	DomainName         string                                        `json:"domainName"`
	Host               string                                        `json:"host"`
	HTTPPort           int64                                         `json:"httpPort"`
	InternalDomainName *string                                       `json:"internalDomainName,omitempty"`
	IPWhitelist        string                                        `json:"ipWhitelist"`
	LbType             string                                        `json:"lbType"`
	Name               string                                        `json:"name"`
	NodeType           string                                        `json:"nodeType"`
	Nodes              int64                                         `json:"nodes"`
	Port               int64                                         `json:"port"`
	PublicEndpoint     bool                                          `json:"publicEndpoint"`
	Region             string                                        `json:"region"`
	Replicas           string                                        `json:"replicas"`
	ReplicateSchema    bool                                          `json:"replicateSchema"`
	Secure             bool                                          `json:"secure"`
	Shards             *int64                                        `json:"shards,omitempty"`
	Size               int64                                         `json:"size"`
	SSHPort            int64                                         `json:"sshPort"`
	StorageClass       string                                        `json:"storageClass"`
	Type               string                                        `json:"type"`
	Uptime             string                                        `json:"uptime"`
	UptimeSettings     ClickhouseClusterRequestInputUptimeSettings   `json:"uptimeSettings"`
	Version            string                                        `json:"version"`
	VersionImage       *string                                       `json:"versionImage,omitempty"`
	Zookeeper          string                                        `json:"zookeeper"`
	ZookeeperOptions   ClickhouseClusterRequestInputZookeeperOptions `json:"zookeeperOptions"`
}
