// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ClickhouseClusterResponseAlertsSettingsRescale struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseAlertsSettingsResume struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseAlertsSettingsStop struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseAlertsSettingsUpgrade struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseAlertsSettings struct {
	Rescale ClickhouseClusterResponseAlertsSettingsRescale `json:"rescale"`
	Resume  ClickhouseClusterResponseAlertsSettingsResume  `json:"resume"`
	Stop    ClickhouseClusterResponseAlertsSettingsStop    `json:"stop"`
	Upgrade ClickhouseClusterResponseAlertsSettingsUpgrade `json:"upgrade"`
}

type ClickhouseClusterResponseBackupOptionsSettings struct {
	Day    int64  `json:"day"`
	Keep   int64  `json:"keep"`
	Period string `json:"period"`
	Time   string `json:"time"`
}

type ClickhouseClusterResponseBackupOptions struct {
	Bucket            string                                           `json:"bucket"`
	CompressionFormat string                                           `json:"compressionFormat"`
	Day               int64                                            `json:"day"`
	Enable            bool                                             `json:"enable"`
	Keep              string                                           `json:"keep"`
	Path              string                                           `json:"path"`
	Provider          string                                           `json:"provider"`
	Region            string                                           `json:"region"`
	Schedule          string                                           `json:"schedule"`
	SecretKey         string                                           `json:"secretKey"`
	Settings          []ClickhouseClusterResponseBackupOptionsSettings `json:"settings"`
	Time              string                                           `json:"time"`
}

type ClickhouseClusterResponseDatadogSettings struct {
	Logs    bool `json:"logs"`
	Metrics bool `json:"metrics"`
}

type ClickhouseClusterResponseEnvironmentBackupOptions struct {
	Bucket            string `json:"bucket"`
	CompressionFormat string `json:"compressionFormat"`
	Day               int64  `json:"day"`
	Enable            bool   `json:"enable"`
	Keep              string `json:"keep"`
	Path              string `json:"path"`
	Provider          string `json:"provider"`
	Region            string `json:"region"`
	Schedule          string `json:"schedule"`
	SecretKey         string `json:"secretKey"`
	Time              string `json:"time"`
}

type ClickhouseClusterResponseEnvironmentDatadogSettings struct {
	Enabled bool   `json:"enabled"`
	Key     string `json:"key"`
	Region  string `json:"region"`
}

type ClickhouseClusterResponseEnvironmentKubeAuthOptions struct {
	CaCert     string `json:"caCert"`
	ClientCert string `json:"clientCert"`
	ClientKey  string `json:"clientKey"`
	Type       string `json:"type"`
}

type ClickhouseClusterResponseEnvironmentLogsStorage struct {
	Bucket string `json:"bucket"`
	Region string `json:"region"`
}

type ClickhouseClusterResponseEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseEnvironmentMonitoringInfoDbClickhouseInKubernetesQueries struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseEnvironmentMonitoringInfoDbLogsDashboard struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseEnvironmentMonitoringInfoDbSystemLoad struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseEnvironmentMonitoringInfoDbZookeeperDashboard struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseEnvironmentMonitoringInfo struct {
	DbAltinityClickhouseOperatorDashboard ClickhouseClusterResponseEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard `json:"db/altinity-clickhouse-operator-dashboard"`
	DbClickhouseInKubernetesQueries       ClickhouseClusterResponseEnvironmentMonitoringInfoDbClickhouseInKubernetesQueries       `json:"db/clickhouse-in-kubernetes-queries"`
	DbLogsDashboard                       ClickhouseClusterResponseEnvironmentMonitoringInfoDbLogsDashboard                       `json:"db/logs-dashboard"`
	DbSystemLoad                          ClickhouseClusterResponseEnvironmentMonitoringInfoDbSystemLoad                          `json:"db/system-load"`
	DbZookeeperDashboard                  ClickhouseClusterResponseEnvironmentMonitoringInfoDbZookeeperDashboard                  `json:"db/zookeeper-dashboard"`
}

type ClickhouseClusterResponseEnvironmentOptions struct {
	Azlist         []string `json:"azlist"`
	Network        string   `json:"network"`
	SizeMultiplier string   `json:"sizeMultiplier"`
}

type ClickhouseClusterResponseEnvironmentResourceLimits struct {
	CPU           string `json:"cpu"`
	Memory        string `json:"memory"`
	Nodes         int64  `json:"nodes"`
	Replicas      int64  `json:"replicas"`
	Shards        int64  `json:"shards"`
	Storage       string `json:"storage"`
	VolumeRescale int64  `json:"volumeRescale"`
}

type ClickhouseClusterResponseEnvironment struct {
	AutoPush            bool                                                `json:"autoPush"`
	AutoZkPush          string                                              `json:"autoZkPush"`
	AwsSettingsAuto     bool                                                `json:"awsSettingsAuto"`
	BackupOptions       ClickhouseClusterResponseEnvironmentBackupOptions   `json:"backupOptions"`
	CoreCIDR            string                                              `json:"coreCIDR"`
	Created             string                                              `json:"created"`
	DashboardURL        string                                              `json:"dashboardUrl"`
	DatadogSettings     ClickhouseClusterResponseEnvironmentDatadogSettings `json:"datadogSettings"`
	Domain              string                                              `json:"domain"`
	ExternalDNS         string                                              `json:"externalDNS"`
	ID                  string                                              `json:"id"`
	IDOwner             string                                              `json:"id_owner"`
	IsAnywhere          bool                                                `json:"isAnywhere"`
	KubeAPIURL          string                                              `json:"kubeAPIUrl"`
	KubeAuthOptions     ClickhouseClusterResponseEnvironmentKubeAuthOptions `json:"kubeAuthOptions"`
	KubeCHOVersion      string                                              `json:"kubeCHOVersion"`
	KubeCheck           string                                              `json:"kubeCheck"`
	KubeLBType          string                                              `json:"kubeLBType"`
	KubeManagedPVs      bool                                                `json:"kubeManagedPVs"`
	KubeNamespace       string                                              `json:"kubeNamespace"`
	KubeNamespaceManage bool                                                `json:"kubeNamespaceManage"`
	KubeProvider        string                                              `json:"kubeProvider"`
	KubeStartupMode     string                                              `json:"kubeStartupMode"`
	KubeToken           string                                              `json:"kubeToken"`
	ListenCheck         string                                              `json:"listenCheck"`
	LogsStorage         ClickhouseClusterResponseEnvironmentLogsStorage     `json:"logsStorage"`
	Monitoring          bool                                                `json:"monitoring"`
	MonitoringInfo      ClickhouseClusterResponseEnvironmentMonitoringInfo  `json:"monitoringInfo"`
	MonitoringURL       string                                              `json:"monitoringUrl"`
	Name                string                                              `json:"name"`
	Options             ClickhouseClusterResponseEnvironmentOptions         `json:"options"`
	Pass                string                                              `json:"pass"`
	ResourceLimits      ClickhouseClusterResponseEnvironmentResourceLimits  `json:"resourceLimits"`
	SniProxyForCH       bool                                                `json:"sniProxyForCH"`
	SslCertificateARN   string                                              `json:"sslCertificateARN"`
	Status              string                                              `json:"status"`
	Type                string                                              `json:"type"`
	User                string                                              `json:"user"`
	VpcEndpoints        bool                                                `json:"vpcEndpoints"`
}

type ClickhouseClusterResponseInitialAction struct {
	User      string `json:"user"`
	UserEmail string `json:"userEmail"`
	UserID    int64  `json:"userId"`
}

type ClickhouseClusterResponseLayoutsReplicatedAlertsSettingsRescale struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseLayoutsReplicatedAlertsSettingsResume struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseLayoutsReplicatedAlertsSettingsStop struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseLayoutsReplicatedAlertsSettingsUpgrade struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseLayoutsReplicatedAlertsSettings struct {
	Rescale ClickhouseClusterResponseLayoutsReplicatedAlertsSettingsRescale `json:"rescale"`
	Resume  ClickhouseClusterResponseLayoutsReplicatedAlertsSettingsResume  `json:"resume"`
	Stop    ClickhouseClusterResponseLayoutsReplicatedAlertsSettingsStop    `json:"stop"`
	Upgrade ClickhouseClusterResponseLayoutsReplicatedAlertsSettingsUpgrade `json:"upgrade"`
}

type ClickhouseClusterResponseLayoutsReplicatedBackupOptions struct {
	Bucket            string `json:"bucket"`
	CompressionFormat string `json:"compressionFormat"`
	Day               int64  `json:"day"`
	Enable            bool   `json:"enable"`
	Keep              string `json:"keep"`
	Path              string `json:"path"`
	Provider          string `json:"provider"`
	Region            string `json:"region"`
	Schedule          string `json:"schedule"`
	SecretKey         string `json:"secretKey"`
	Time              string `json:"time"`
}

type ClickhouseClusterResponseLayoutsReplicatedDatadogSettings struct {
	Logs    bool `json:"logs"`
	Metrics bool `json:"metrics"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentBackupOptions struct {
	Bucket            string `json:"bucket"`
	CompressionFormat string `json:"compressionFormat"`
	Day               int64  `json:"day"`
	Enable            bool   `json:"enable"`
	Keep              string `json:"keep"`
	Path              string `json:"path"`
	Provider          string `json:"provider"`
	Region            string `json:"region"`
	Schedule          string `json:"schedule"`
	SecretKey         string `json:"secretKey"`
	Time              string `json:"time"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentDatadogSettings struct {
	Enabled bool   `json:"enabled"`
	Key     string `json:"key"`
	Region  string `json:"region"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentKubeAuthOptions struct {
	CaCert     string `json:"caCert"`
	ClientCert string `json:"clientCert"`
	ClientKey  string `json:"clientKey"`
	Type       string `json:"type"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentLogsStorage struct {
	Bucket string `json:"bucket"`
	Region string `json:"region"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfoDbClickhouseInKubernetesQueries struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfoDbLogsDashboard struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfoDbSystemLoad struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfoDbZookeeperDashboard struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfo struct {
	DbAltinityClickhouseOperatorDashboard ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard `json:"db/altinity-clickhouse-operator-dashboard"`
	DbClickhouseInKubernetesQueries       ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfoDbClickhouseInKubernetesQueries       `json:"db/clickhouse-in-kubernetes-queries"`
	DbLogsDashboard                       ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfoDbLogsDashboard                       `json:"db/logs-dashboard"`
	DbSystemLoad                          ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfoDbSystemLoad                          `json:"db/system-load"`
	DbZookeeperDashboard                  ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfoDbZookeeperDashboard                  `json:"db/zookeeper-dashboard"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentOptions struct {
	Azlist         []string `json:"azlist"`
	Network        string   `json:"network"`
	SizeMultiplier string   `json:"sizeMultiplier"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironmentResourceLimits struct {
	CPU           string `json:"cpu"`
	Memory        string `json:"memory"`
	Nodes         int64  `json:"nodes"`
	Replicas      int64  `json:"replicas"`
	Shards        int64  `json:"shards"`
	Storage       string `json:"storage"`
	VolumeRescale int64  `json:"volumeRescale"`
}

type ClickhouseClusterResponseLayoutsReplicatedEnvironment struct {
	AutoPush            bool                                                                 `json:"autoPush"`
	AutoZkPush          string                                                               `json:"autoZkPush"`
	AwsSettingsAuto     bool                                                                 `json:"awsSettingsAuto"`
	BackupOptions       ClickhouseClusterResponseLayoutsReplicatedEnvironmentBackupOptions   `json:"backupOptions"`
	CoreCIDR            string                                                               `json:"coreCIDR"`
	Created             string                                                               `json:"created"`
	DashboardURL        string                                                               `json:"dashboardUrl"`
	DatadogSettings     ClickhouseClusterResponseLayoutsReplicatedEnvironmentDatadogSettings `json:"datadogSettings"`
	Domain              string                                                               `json:"domain"`
	ExternalDNS         string                                                               `json:"externalDNS"`
	ID                  string                                                               `json:"id"`
	IDOwner             string                                                               `json:"id_owner"`
	IsAnywhere          bool                                                                 `json:"isAnywhere"`
	KubeAPIURL          string                                                               `json:"kubeAPIUrl"`
	KubeAuthOptions     ClickhouseClusterResponseLayoutsReplicatedEnvironmentKubeAuthOptions `json:"kubeAuthOptions"`
	KubeCHOVersion      string                                                               `json:"kubeCHOVersion"`
	KubeCheck           string                                                               `json:"kubeCheck"`
	KubeLBType          string                                                               `json:"kubeLBType"`
	KubeManagedPVs      bool                                                                 `json:"kubeManagedPVs"`
	KubeNamespace       string                                                               `json:"kubeNamespace"`
	KubeNamespaceManage bool                                                                 `json:"kubeNamespaceManage"`
	KubeProvider        string                                                               `json:"kubeProvider"`
	KubeStartupMode     string                                                               `json:"kubeStartupMode"`
	KubeToken           string                                                               `json:"kubeToken"`
	ListenCheck         string                                                               `json:"listenCheck"`
	LogsStorage         ClickhouseClusterResponseLayoutsReplicatedEnvironmentLogsStorage     `json:"logsStorage"`
	Monitoring          bool                                                                 `json:"monitoring"`
	MonitoringInfo      ClickhouseClusterResponseLayoutsReplicatedEnvironmentMonitoringInfo  `json:"monitoringInfo"`
	MonitoringURL       string                                                               `json:"monitoringUrl"`
	Name                string                                                               `json:"name"`
	Options             ClickhouseClusterResponseLayoutsReplicatedEnvironmentOptions         `json:"options"`
	Pass                string                                                               `json:"pass"`
	ResourceLimits      ClickhouseClusterResponseLayoutsReplicatedEnvironmentResourceLimits  `json:"resourceLimits"`
	SniProxyForCH       bool                                                                 `json:"sniProxyForCH"`
	SslCertificateARN   string                                                               `json:"sslCertificateARN"`
	Status              string                                                               `json:"status"`
	Type                string                                                               `json:"type"`
	User                string                                                               `json:"user"`
	VpcEndpoints        bool                                                                 `json:"vpcEndpoints"`
}

type ClickhouseClusterResponseLayoutsReplicatedInitialAction struct {
	User      string `json:"user"`
	UserEmail string `json:"userEmail"`
	UserID    int64  `json:"userId"`
}

type ClickhouseClusterResponseLayoutsReplicatedOwnerOrganization struct {
	AutoCharge        bool   `json:"autoCharge"`
	Blocked           bool   `json:"blocked"`
	BlockedAPI        bool   `json:"blockedAPI"`
	BlockedPassword   bool   `json:"blockedPassword"`
	CompanyName       string `json:"companyName"`
	EmailDomain       string `json:"emailDomain"`
	Expired           bool   `json:"expired"`
	ID                string `json:"id"`
	IDDefaultUserRole string `json:"id_defaultUserRole"`
	IDOwner           string `json:"id_owner"`
	Name              string `json:"name"`
	Opened            bool   `json:"opened"`
	Trial             bool   `json:"trial"`
	TrialExpiry       string `json:"trialExpiry"`
}

type ClickhouseClusterResponseLayoutsReplicatedOwnerRoleRights struct {
	Access string `json:"access"`
	Action string `json:"action"`
	Class  string `json:"class"`
}

type ClickhouseClusterResponseLayoutsReplicatedOwnerRole struct {
	ID     string                                                      `json:"id"`
	Name   string                                                      `json:"name"`
	Rights []ClickhouseClusterResponseLayoutsReplicatedOwnerRoleRights `json:"rights"`
	System bool                                                        `json:"system"`
}

type ClickhouseClusterResponseLayoutsReplicatedOwner struct {
	BackupTool     string                                                      `json:"backupTool"`
	Blocked        bool                                                        `json:"blocked"`
	DarkTheme      bool                                                        `json:"darkTheme"`
	Email          string                                                      `json:"email"`
	ID             string                                                      `json:"id"`
	IDOrganization string                                                      `json:"id_organization"`
	IDRole         string                                                      `json:"id_role"`
	Name           string                                                      `json:"name"`
	Organization   ClickhouseClusterResponseLayoutsReplicatedOwnerOrganization `json:"organization"`
	Origins        string                                                      `json:"origins"`
	Password       string                                                      `json:"password"`
	Role           ClickhouseClusterResponseLayoutsReplicatedOwnerRole         `json:"role"`
}

type ClickhouseClusterResponseLayoutsReplicated struct {
	AlertsSettings       ClickhouseClusterResponseLayoutsReplicatedAlertsSettings  `json:"alertsSettings"`
	AlternateEndpoints   []interface{}                                             `json:"alternateEndpoints"`
	BackupOptions        ClickhouseClusterResponseLayoutsReplicatedBackupOptions   `json:"backupOptions"`
	CanPublish           bool                                                      `json:"canPublish"`
	CanRescale           bool                                                      `json:"canRescale"`
	ClusterMonitoringURL string                                                    `json:"clusterMonitoringUrl"`
	DatadogSettings      ClickhouseClusterResponseLayoutsReplicatedDatadogSettings `json:"datadogSettings"`
	Environment          ClickhouseClusterResponseLayoutsReplicatedEnvironment     `json:"environment"`
	HasChanges           bool                                                      `json:"hasChanges"`
	HasMigration         bool                                                      `json:"hasMigration"`
	ID                   string                                                    `json:"id"`
	IDEnvironment        string                                                    `json:"id_environment"`
	IDOwner              string                                                    `json:"id_owner"`
	IDParent             string                                                    `json:"id_parent"`
	InitialAction        ClickhouseClusterResponseLayoutsReplicatedInitialAction   `json:"initialAction"`
	InternalName         string                                                    `json:"internalName"`
	Layouts              []interface{}                                             `json:"layouts"`
	LogsMonitoringURL    string                                                    `json:"logsMonitoringUrl"`
	MigrationProgress    int64                                                     `json:"migrationProgress"`
	MysqlProtocol        bool                                                      `json:"mysqlProtocol"`
	Name                 string                                                    `json:"name"`
	NormalizedName       string                                                    `json:"normalizedName"`
	Owner                ClickhouseClusterResponseLayoutsReplicatedOwner           `json:"owner"`
	QueryMonitoringURL   string                                                    `json:"queryMonitoringUrl"`
	Replicas             int64                                                     `json:"replicas"`
	Secure               bool                                                      `json:"secure"`
	Shards               int64                                                     `json:"shards"`
	SystemMonitoringURL  string                                                    `json:"systemMonitoringUrl"`
	SystemVersion        string                                                    `json:"systemVersion"`
	Uptime               string                                                    `json:"uptime"`
	UptimeSettings       []interface{}                                             `json:"uptimeSettings"`
	Version              string                                                    `json:"version"`
}

type ClickhouseClusterResponseLayoutsShardedAlertsSettingsRescale struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseLayoutsShardedAlertsSettingsResume struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseLayoutsShardedAlertsSettingsStop struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseLayoutsShardedAlertsSettingsUpgrade struct {
	Email bool `json:"email"`
	Popup bool `json:"popup"`
}

type ClickhouseClusterResponseLayoutsShardedAlertsSettings struct {
	Rescale ClickhouseClusterResponseLayoutsShardedAlertsSettingsRescale `json:"rescale"`
	Resume  ClickhouseClusterResponseLayoutsShardedAlertsSettingsResume  `json:"resume"`
	Stop    ClickhouseClusterResponseLayoutsShardedAlertsSettingsStop    `json:"stop"`
	Upgrade ClickhouseClusterResponseLayoutsShardedAlertsSettingsUpgrade `json:"upgrade"`
}

type ClickhouseClusterResponseLayoutsShardedBackupOptions struct {
	Bucket            string `json:"bucket"`
	CompressionFormat string `json:"compressionFormat"`
	Day               int64  `json:"day"`
	Enable            bool   `json:"enable"`
	Keep              string `json:"keep"`
	Path              string `json:"path"`
	Provider          string `json:"provider"`
	Region            string `json:"region"`
	Schedule          string `json:"schedule"`
	SecretKey         string `json:"secretKey"`
	Time              string `json:"time"`
}

type ClickhouseClusterResponseLayoutsShardedDatadogSettings struct {
	Logs    bool `json:"logs"`
	Metrics bool `json:"metrics"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentBackupOptions struct {
	Bucket            string `json:"bucket"`
	CompressionFormat string `json:"compressionFormat"`
	Day               int64  `json:"day"`
	Enable            bool   `json:"enable"`
	Keep              string `json:"keep"`
	Path              string `json:"path"`
	Provider          string `json:"provider"`
	Region            string `json:"region"`
	Schedule          string `json:"schedule"`
	SecretKey         string `json:"secretKey"`
	Time              string `json:"time"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentDatadogSettings struct {
	Enabled bool   `json:"enabled"`
	Key     string `json:"key"`
	Region  string `json:"region"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentKubeAuthOptions struct {
	CaCert     string `json:"caCert"`
	ClientCert string `json:"clientCert"`
	ClientKey  string `json:"clientKey"`
	Type       string `json:"type"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentLogsStorage struct {
	Bucket string `json:"bucket"`
	Region string `json:"region"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfoDbClickhouseInKubernetesQueries struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfoDbLogsDashboard struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfoDbSystemLoad struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfoDbZookeeperDashboard struct {
	UID string `json:"uid"`
	URL string `json:"url"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfo struct {
	DbAltinityClickhouseOperatorDashboard ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard `json:"db/altinity-clickhouse-operator-dashboard"`
	DbClickhouseInKubernetesQueries       ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfoDbClickhouseInKubernetesQueries       `json:"db/clickhouse-in-kubernetes-queries"`
	DbLogsDashboard                       ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfoDbLogsDashboard                       `json:"db/logs-dashboard"`
	DbSystemLoad                          ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfoDbSystemLoad                          `json:"db/system-load"`
	DbZookeeperDashboard                  ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfoDbZookeeperDashboard                  `json:"db/zookeeper-dashboard"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentOptions struct {
	Azlist         []string `json:"azlist"`
	Network        string   `json:"network"`
	SizeMultiplier string   `json:"sizeMultiplier"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironmentResourceLimits struct {
	CPU           string `json:"cpu"`
	Memory        string `json:"memory"`
	Nodes         int64  `json:"nodes"`
	Replicas      int64  `json:"replicas"`
	Shards        int64  `json:"shards"`
	Storage       string `json:"storage"`
	VolumeRescale int64  `json:"volumeRescale"`
}

type ClickhouseClusterResponseLayoutsShardedEnvironment struct {
	AutoPush            bool                                                              `json:"autoPush"`
	AutoZkPush          string                                                            `json:"autoZkPush"`
	AwsSettingsAuto     bool                                                              `json:"awsSettingsAuto"`
	BackupOptions       ClickhouseClusterResponseLayoutsShardedEnvironmentBackupOptions   `json:"backupOptions"`
	CoreCIDR            string                                                            `json:"coreCIDR"`
	Created             string                                                            `json:"created"`
	DashboardURL        string                                                            `json:"dashboardUrl"`
	DatadogSettings     ClickhouseClusterResponseLayoutsShardedEnvironmentDatadogSettings `json:"datadogSettings"`
	Domain              string                                                            `json:"domain"`
	ExternalDNS         string                                                            `json:"externalDNS"`
	ID                  string                                                            `json:"id"`
	IDOwner             string                                                            `json:"id_owner"`
	IsAnywhere          bool                                                              `json:"isAnywhere"`
	KubeAPIURL          string                                                            `json:"kubeAPIUrl"`
	KubeAuthOptions     ClickhouseClusterResponseLayoutsShardedEnvironmentKubeAuthOptions `json:"kubeAuthOptions"`
	KubeCHOVersion      string                                                            `json:"kubeCHOVersion"`
	KubeCheck           string                                                            `json:"kubeCheck"`
	KubeLBType          string                                                            `json:"kubeLBType"`
	KubeManagedPVs      bool                                                              `json:"kubeManagedPVs"`
	KubeNamespace       string                                                            `json:"kubeNamespace"`
	KubeNamespaceManage bool                                                              `json:"kubeNamespaceManage"`
	KubeProvider        string                                                            `json:"kubeProvider"`
	KubeStartupMode     string                                                            `json:"kubeStartupMode"`
	KubeToken           string                                                            `json:"kubeToken"`
	ListenCheck         string                                                            `json:"listenCheck"`
	LogsStorage         ClickhouseClusterResponseLayoutsShardedEnvironmentLogsStorage     `json:"logsStorage"`
	Monitoring          bool                                                              `json:"monitoring"`
	MonitoringInfo      ClickhouseClusterResponseLayoutsShardedEnvironmentMonitoringInfo  `json:"monitoringInfo"`
	MonitoringURL       string                                                            `json:"monitoringUrl"`
	Name                string                                                            `json:"name"`
	Options             ClickhouseClusterResponseLayoutsShardedEnvironmentOptions         `json:"options"`
	Pass                string                                                            `json:"pass"`
	ResourceLimits      ClickhouseClusterResponseLayoutsShardedEnvironmentResourceLimits  `json:"resourceLimits"`
	SniProxyForCH       bool                                                              `json:"sniProxyForCH"`
	SslCertificateARN   string                                                            `json:"sslCertificateARN"`
	Status              string                                                            `json:"status"`
	Type                string                                                            `json:"type"`
	User                string                                                            `json:"user"`
	VpcEndpoints        bool                                                              `json:"vpcEndpoints"`
}

type ClickhouseClusterResponseLayoutsShardedInitialAction struct {
	User      string `json:"user"`
	UserEmail string `json:"userEmail"`
	UserID    int64  `json:"userId"`
}

type ClickhouseClusterResponseLayoutsShardedOwnerOrganization struct {
	AutoCharge        bool   `json:"autoCharge"`
	Blocked           bool   `json:"blocked"`
	BlockedAPI        bool   `json:"blockedAPI"`
	BlockedPassword   bool   `json:"blockedPassword"`
	CompanyName       string `json:"companyName"`
	EmailDomain       string `json:"emailDomain"`
	Expired           bool   `json:"expired"`
	ID                string `json:"id"`
	IDDefaultUserRole string `json:"id_defaultUserRole"`
	IDOwner           string `json:"id_owner"`
	Name              string `json:"name"`
	Opened            bool   `json:"opened"`
	Trial             bool   `json:"trial"`
	TrialExpiry       string `json:"trialExpiry"`
}

type ClickhouseClusterResponseLayoutsShardedOwnerRoleRights struct {
	Access string `json:"access"`
	Action string `json:"action"`
	Class  string `json:"class"`
}

type ClickhouseClusterResponseLayoutsShardedOwnerRole struct {
	ID     string                                                   `json:"id"`
	Name   string                                                   `json:"name"`
	Rights []ClickhouseClusterResponseLayoutsShardedOwnerRoleRights `json:"rights"`
	System bool                                                     `json:"system"`
}

type ClickhouseClusterResponseLayoutsShardedOwner struct {
	BackupTool     string                                                   `json:"backupTool"`
	Blocked        bool                                                     `json:"blocked"`
	DarkTheme      bool                                                     `json:"darkTheme"`
	Email          string                                                   `json:"email"`
	ID             string                                                   `json:"id"`
	IDOrganization string                                                   `json:"id_organization"`
	IDRole         string                                                   `json:"id_role"`
	Name           string                                                   `json:"name"`
	Organization   ClickhouseClusterResponseLayoutsShardedOwnerOrganization `json:"organization"`
	Origins        string                                                   `json:"origins"`
	Password       string                                                   `json:"password"`
	Role           ClickhouseClusterResponseLayoutsShardedOwnerRole         `json:"role"`
}

type ClickhouseClusterResponseLayoutsSharded struct {
	AlertsSettings       ClickhouseClusterResponseLayoutsShardedAlertsSettings  `json:"alertsSettings"`
	AlternateEndpoints   []interface{}                                          `json:"alternateEndpoints"`
	BackupOptions        ClickhouseClusterResponseLayoutsShardedBackupOptions   `json:"backupOptions"`
	CanPublish           bool                                                   `json:"canPublish"`
	CanRescale           bool                                                   `json:"canRescale"`
	ClusterMonitoringURL string                                                 `json:"clusterMonitoringUrl"`
	DatadogSettings      ClickhouseClusterResponseLayoutsShardedDatadogSettings `json:"datadogSettings"`
	Environment          ClickhouseClusterResponseLayoutsShardedEnvironment     `json:"environment"`
	HasChanges           bool                                                   `json:"hasChanges"`
	HasMigration         bool                                                   `json:"hasMigration"`
	ID                   string                                                 `json:"id"`
	IDEnvironment        string                                                 `json:"id_environment"`
	IDOwner              string                                                 `json:"id_owner"`
	IDParent             string                                                 `json:"id_parent"`
	InitialAction        ClickhouseClusterResponseLayoutsShardedInitialAction   `json:"initialAction"`
	InternalName         string                                                 `json:"internalName"`
	Layouts              []interface{}                                          `json:"layouts"`
	LogsMonitoringURL    string                                                 `json:"logsMonitoringUrl"`
	MigrationProgress    int64                                                  `json:"migrationProgress"`
	MysqlProtocol        bool                                                   `json:"mysqlProtocol"`
	Name                 string                                                 `json:"name"`
	Nodes                []interface{}                                          `json:"nodes"`
	NormalizedName       string                                                 `json:"normalizedName"`
	Owner                ClickhouseClusterResponseLayoutsShardedOwner           `json:"owner"`
	QueryMonitoringURL   string                                                 `json:"queryMonitoringUrl"`
	Replicas             int64                                                  `json:"replicas"`
	Secure               bool                                                   `json:"secure"`
	Shards               int64                                                  `json:"shards"`
	SystemMonitoringURL  string                                                 `json:"systemMonitoringUrl"`
	SystemVersion        string                                                 `json:"systemVersion"`
	Uptime               string                                                 `json:"uptime"`
	UptimeSettings       []interface{}                                          `json:"uptimeSettings"`
	Version              string                                                 `json:"version"`
}

type ClickhouseClusterResponseLayouts struct {
	Replicated ClickhouseClusterResponseLayoutsReplicated `json:"replicated"`
	Sharded    ClickhouseClusterResponseLayoutsSharded    `json:"sharded"`
}

type ClickhouseClusterResponseOptions struct {
	AcmHost      string   `json:"acmHost"`
	Azlist       []string `json:"azlist"`
	CPU          string   `json:"cpu"`
	Disks        int64    `json:"disks"`
	IPWhitelist  string   `json:"ipWhitelist"`
	LbType       string   `json:"lbType"`
	ManagedPVs   bool     `json:"managedPVs"`
	Memory       string   `json:"memory"`
	Region       string   `json:"region"`
	Size         int64    `json:"size"`
	Static       bool     `json:"static"`
	StorageClass string   `json:"storageClass"`
	Type         string   `json:"type"`
	Version      string   `json:"version"`
	ZkRoot       bool     `json:"zkRoot"`
}

type ClickhouseClusterResponseOwnerOrganization struct {
	AutoCharge        bool   `json:"autoCharge"`
	Blocked           bool   `json:"blocked"`
	BlockedAPI        bool   `json:"blockedAPI"`
	BlockedPassword   bool   `json:"blockedPassword"`
	CompanyName       string `json:"companyName"`
	EmailDomain       string `json:"emailDomain"`
	Expired           bool   `json:"expired"`
	ID                string `json:"id"`
	IDDefaultUserRole string `json:"id_defaultUserRole"`
	IDOwner           string `json:"id_owner"`
	Name              string `json:"name"`
	Opened            bool   `json:"opened"`
	Trial             bool   `json:"trial"`
	TrialExpiry       string `json:"trialExpiry"`
}

type ClickhouseClusterResponseOwnerRoleRights struct {
	Access string `json:"access"`
	Action string `json:"action"`
	Class  string `json:"class"`
}

type ClickhouseClusterResponseOwnerRole struct {
	ID     string                                     `json:"id"`
	Name   string                                     `json:"name"`
	Rights []ClickhouseClusterResponseOwnerRoleRights `json:"rights"`
	System bool                                       `json:"system"`
}

type ClickhouseClusterResponseOwner struct {
	BackupTool     string                                     `json:"backupTool"`
	Blocked        bool                                       `json:"blocked"`
	DarkTheme      bool                                       `json:"darkTheme"`
	Email          string                                     `json:"email"`
	ID             string                                     `json:"id"`
	IDOrganization string                                     `json:"id_organization"`
	IDRole         string                                     `json:"id_role"`
	Name           string                                     `json:"name"`
	Organization   ClickhouseClusterResponseOwnerOrganization `json:"organization"`
	Origins        string                                     `json:"origins"`
	Password       string                                     `json:"password"`
	Role           ClickhouseClusterResponseOwnerRole         `json:"role"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleFriRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleFri struct {
	Active bool                                                    `json:"active"`
	AllDay bool                                                    `json:"allDay"`
	Range  ClickhouseClusterResponseUptimeSettingsScheduleFriRange `json:"range"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleMonRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleMon struct {
	Active bool                                                    `json:"active"`
	AllDay bool                                                    `json:"allDay"`
	Range  ClickhouseClusterResponseUptimeSettingsScheduleMonRange `json:"range"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleSatRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleSat struct {
	Active bool                                                    `json:"active"`
	AllDay bool                                                    `json:"allDay"`
	Range  ClickhouseClusterResponseUptimeSettingsScheduleSatRange `json:"range"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleSunRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleSun struct {
	Active bool                                                    `json:"active"`
	AllDay bool                                                    `json:"allDay"`
	Range  ClickhouseClusterResponseUptimeSettingsScheduleSunRange `json:"range"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleThuRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleThu struct {
	Active bool                                                    `json:"active"`
	AllDay bool                                                    `json:"allDay"`
	Range  ClickhouseClusterResponseUptimeSettingsScheduleThuRange `json:"range"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleTueRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleTue struct {
	Active bool                                                    `json:"active"`
	AllDay bool                                                    `json:"allDay"`
	Range  ClickhouseClusterResponseUptimeSettingsScheduleTueRange `json:"range"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleWedRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type ClickhouseClusterResponseUptimeSettingsScheduleWed struct {
	Active bool                                                    `json:"active"`
	AllDay bool                                                    `json:"allDay"`
	Range  ClickhouseClusterResponseUptimeSettingsScheduleWedRange `json:"range"`
}

type ClickhouseClusterResponseUptimeSettingsSchedule struct {
	Fri ClickhouseClusterResponseUptimeSettingsScheduleFri `json:"fri"`
	Mon ClickhouseClusterResponseUptimeSettingsScheduleMon `json:"mon"`
	Sat ClickhouseClusterResponseUptimeSettingsScheduleSat `json:"sat"`
	Sun ClickhouseClusterResponseUptimeSettingsScheduleSun `json:"sun"`
	Thu ClickhouseClusterResponseUptimeSettingsScheduleThu `json:"thu"`
	Tue ClickhouseClusterResponseUptimeSettingsScheduleTue `json:"tue"`
	Wed ClickhouseClusterResponseUptimeSettingsScheduleWed `json:"wed"`
}

type ClickhouseClusterResponseUptimeSettings struct {
	InactiveHours int64                                           `json:"inactiveHours"`
	Schedule      ClickhouseClusterResponseUptimeSettingsSchedule `json:"schedule"`
}

type ClickhouseClusterResponse struct {
	AdminPass            string                                   `json:"adminPass"`
	AlertsSettings       ClickhouseClusterResponseAlertsSettings  `json:"alertsSettings"`
	AlternateEndpoints   []interface{}                            `json:"alternateEndpoints"`
	AltinitySupport      string                                   `json:"altinitySupport"`
	BackupOptions        ClickhouseClusterResponseBackupOptions   `json:"backupOptions"`
	CanPublish           bool                                     `json:"canPublish"`
	CanRescale           bool                                     `json:"canRescale"`
	ClusterMonitoringURL string                                   `json:"clusterMonitoringUrl"`
	DatadogSettings      ClickhouseClusterResponseDatadogSettings `json:"datadogSettings"`
	Environment          ClickhouseClusterResponseEnvironment     `json:"environment"`
	HasChanges           bool                                     `json:"hasChanges"`
	HasMigration         bool                                     `json:"hasMigration"`
	ID                   string                                   `json:"id"`
	IDEnvironment        string                                   `json:"id_environment"`
	IDOwner              string                                   `json:"id_owner"`
	InitialAction        ClickhouseClusterResponseInitialAction   `json:"initialAction"`
	InternalName         string                                   `json:"internalName"`
	Layouts              ClickhouseClusterResponseLayouts         `json:"layouts"`
	LogsMonitoringURL    string                                   `json:"logsMonitoringUrl"`
	MigrationProgress    int64                                    `json:"migrationProgress"`
	MysqlProtocol        bool                                     `json:"mysqlProtocol"`
	Name                 string                                   `json:"name"`
	Nodes                []interface{}                            `json:"nodes"`
	NormalizedName       string                                   `json:"normalizedName"`
	Options              ClickhouseClusterResponseOptions         `json:"options"`
	Owner                ClickhouseClusterResponseOwner           `json:"owner"`
	QueryMonitoringURL   string                                   `json:"queryMonitoringUrl"`
	Secure               bool                                     `json:"secure"`
	Shards               int64                                    `json:"shards"`
	StartupMode          string                                   `json:"startupMode"`
	Status               string                                   `json:"status"`
	SystemMonitoringURL  string                                   `json:"systemMonitoringUrl"`
	SystemVersion        string                                   `json:"systemVersion"`
	Uptime               string                                   `json:"uptime"`
	UptimeSettings       ClickhouseClusterResponseUptimeSettings  `json:"uptimeSettings"`
	Version              string                                   `json:"version"`
}
