// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterRequestInputZookeeperOptions struct {
	Root types.String `tfsdk:"root"`
	Size types.String `tfsdk:"size"`
	Tag  types.String `tfsdk:"tag"`
}
