// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseLayoutsReplicated struct {
	AlertsSettings       ClickhouseClusterResponseAlertsSettings                   `tfsdk:"alerts_settings"`
	AlternateEndpoints   []types.String                                            `tfsdk:"alternate_endpoints"`
	BackupOptions        ClickhouseClusterResponseEnvironmentBackupOptions         `tfsdk:"backup_options"`
	CanPublish           types.Bool                                                `tfsdk:"can_publish"`
	CanRescale           types.Bool                                                `tfsdk:"can_rescale"`
	ClusterMonitoringURL types.String                                              `tfsdk:"cluster_monitoring_url"`
	DatadogSettings      ClickhouseClusterResponseLayoutsReplicatedDatadogSettings `tfsdk:"datadog_settings"`
	Environment          ClickhouseClusterResponseEnvironment                      `tfsdk:"environment"`
	HasChanges           types.Bool                                                `tfsdk:"has_changes"`
	HasMigration         types.Bool                                                `tfsdk:"has_migration"`
	ID                   types.String                                              `tfsdk:"id"`
	IDEnvironment        types.String                                              `tfsdk:"id_environment"`
	IDOwner              types.String                                              `tfsdk:"id_owner"`
	IDParent             types.String                                              `tfsdk:"id_parent"`
	InitialAction        ClickhouseClusterResponseInitialAction                    `tfsdk:"initial_action"`
	InternalName         types.String                                              `tfsdk:"internal_name"`
	Layouts              []types.String                                            `tfsdk:"layouts"`
	LogsMonitoringURL    types.String                                              `tfsdk:"logs_monitoring_url"`
	MigrationProgress    types.Int64                                               `tfsdk:"migration_progress"`
	MysqlProtocol        types.Bool                                                `tfsdk:"mysql_protocol"`
	Name                 types.String                                              `tfsdk:"name"`
	NormalizedName       types.String                                              `tfsdk:"normalized_name"`
	Owner                ClickhouseClusterResponseLayoutsReplicatedOwner           `tfsdk:"owner"`
	QueryMonitoringURL   types.String                                              `tfsdk:"query_monitoring_url"`
	Replicas             types.Int64                                               `tfsdk:"replicas"`
	Secure               types.Bool                                                `tfsdk:"secure"`
	Shards               types.Int64                                               `tfsdk:"shards"`
	SystemMonitoringURL  types.String                                              `tfsdk:"system_monitoring_url"`
	SystemVersion        types.String                                              `tfsdk:"system_version"`
	Uptime               types.String                                              `tfsdk:"uptime"`
	UptimeSettings       []types.String                                            `tfsdk:"uptime_settings"`
	Version              types.String                                              `tfsdk:"version"`
}
