// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseLayoutsReplicatedOwnerRoleRights struct {
	Access types.String `tfsdk:"access"`
	Action types.String `tfsdk:"action"`
	Class  types.String `tfsdk:"class"`
}
