// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseInitialAction struct {
	User      types.String `tfsdk:"user"`
	UserEmail types.String `tfsdk:"user_email"`
	UserID    types.Int64  `tfsdk:"user_id"`
}
