// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseUptimeSettingsScheduleFri struct {
	Active types.Bool                                              `tfsdk:"active"`
	AllDay types.Bool                                              `tfsdk:"all_day"`
	Range  ClickhouseClusterResponseUptimeSettingsScheduleFriRange `tfsdk:"range"`
}
