// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard struct {
	UID types.String `tfsdk:"uid"`
	URL types.String `tfsdk:"url"`
}
