// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseOptions struct {
	AcmHost      types.String   `tfsdk:"acm_host"`
	Azlist       []types.String `tfsdk:"azlist"`
	CPU          types.String   `tfsdk:"cpu"`
	Disks        types.Int64    `tfsdk:"disks"`
	IPWhitelist  types.String   `tfsdk:"ip_whitelist"`
	LbType       types.String   `tfsdk:"lb_type"`
	ManagedPVs   types.Bool     `tfsdk:"managed_p_vs"`
	Memory       types.String   `tfsdk:"memory"`
	Region       types.String   `tfsdk:"region"`
	Size         types.Int64    `tfsdk:"size"`
	Static       types.Bool     `tfsdk:"static"`
	StorageClass types.String   `tfsdk:"storage_class"`
	Type         types.String   `tfsdk:"type"`
	Version      types.String   `tfsdk:"version"`
	ZkRoot       types.Bool     `tfsdk:"zk_root"`
}
