// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseBackupOptionsSettings struct {
	Day    types.Int64  `tfsdk:"day"`
	Keep   types.Int64  `tfsdk:"keep"`
	Period types.String `tfsdk:"period"`
	Time   types.String `tfsdk:"time"`
}
