// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type ClickhouseClusterResponseEnvironmentMonitoringInfo struct {
	DbAltinityClickhouseOperatorDashboard ClickhouseClusterResponseEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard `tfsdk:"db_altinity_clickhouse_operator_dashboard"`
	DbClickhouseInKubernetesQueries       ClickhouseClusterResponseEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard `tfsdk:"db_clickhouse_in_kubernetes_queries"`
	DbLogsDashboard                       ClickhouseClusterResponseEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard `tfsdk:"db_logs_dashboard"`
	DbSystemLoad                          ClickhouseClusterResponseEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard `tfsdk:"db_system_load"`
	DbZookeeperDashboard                  ClickhouseClusterResponseEnvironmentMonitoringInfoDbAltinityClickhouseOperatorDashboard `tfsdk:"db_zookeeper_dashboard"`
}
