// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type ClickhouseClusterResponseUptimeSettingsSchedule struct {
	Fri ClickhouseClusterResponseUptimeSettingsScheduleFri `tfsdk:"fri"`
	Mon ClickhouseClusterResponseUptimeSettingsScheduleFri `tfsdk:"mon"`
	Sat ClickhouseClusterResponseUptimeSettingsScheduleFri `tfsdk:"sat"`
	Sun ClickhouseClusterResponseUptimeSettingsScheduleFri `tfsdk:"sun"`
	Thu ClickhouseClusterResponseUptimeSettingsScheduleFri `tfsdk:"thu"`
	Tue ClickhouseClusterResponseUptimeSettingsScheduleFri `tfsdk:"tue"`
	Wed ClickhouseClusterResponseUptimeSettingsScheduleFri `tfsdk:"wed"`
}
