// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseEnvironmentBackupOptions struct {
	Bucket            types.String `tfsdk:"bucket"`
	CompressionFormat types.String `tfsdk:"compression_format"`
	Day               types.Int64  `tfsdk:"day"`
	Enable            types.Bool   `tfsdk:"enable"`
	Keep              types.String `tfsdk:"keep"`
	Path              types.String `tfsdk:"path"`
	Provider          types.String `tfsdk:"provider"`
	Region            types.String `tfsdk:"region"`
	Schedule          types.String `tfsdk:"schedule"`
	SecretKey         types.String `tfsdk:"secret_key"`
	Time              types.String `tfsdk:"time"`
}
