// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type ClickhouseClusterResponseAlertsSettings struct {
	Rescale ClickhouseClusterResponseAlertsSettingsRescale `tfsdk:"rescale"`
	Resume  ClickhouseClusterResponseAlertsSettingsRescale `tfsdk:"resume"`
	Stop    ClickhouseClusterResponseAlertsSettingsRescale `tfsdk:"stop"`
	Upgrade ClickhouseClusterResponseAlertsSettingsRescale `tfsdk:"upgrade"`
}
