// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseUptimeSettingsScheduleFriRange struct {
	From types.String `tfsdk:"from"`
	To   types.String `tfsdk:"to"`
}
