// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type ClickhouseClusterResponseLayouts struct {
	Replicated ClickhouseClusterResponseLayoutsReplicated `tfsdk:"replicated"`
	Sharded    ClickhouseClusterResponseLayoutsSharded    `tfsdk:"sharded"`
}
