// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseEnvironmentOptions struct {
	Azlist         []types.String `tfsdk:"azlist"`
	Network        types.String   `tfsdk:"network"`
	SizeMultiplier types.String   `tfsdk:"size_multiplier"`
}
