// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseEnvironmentDatadogSettings struct {
	Enabled types.Bool   `tfsdk:"enabled"`
	Key     types.String `tfsdk:"key"`
	Region  types.String `tfsdk:"region"`
}
