// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseLayoutsReplicatedOwnerRole struct {
	ID     types.String                                                `tfsdk:"id"`
	Name   types.String                                                `tfsdk:"name"`
	Rights []ClickhouseClusterResponseLayoutsReplicatedOwnerRoleRights `tfsdk:"rights"`
	System types.Bool                                                  `tfsdk:"system"`
}
