// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseAlertsSettingsRescale struct {
	Email types.Bool `tfsdk:"email"`
	Popup types.Bool `tfsdk:"popup"`
}
