// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ClickhouseClusterResponseEnvironment struct {
	AutoPush            types.Bool                                          `tfsdk:"auto_push"`
	AutoZkPush          types.String                                        `tfsdk:"auto_zk_push"`
	AwsSettingsAuto     types.Bool                                          `tfsdk:"aws_settings_auto"`
	BackupOptions       ClickhouseClusterResponseEnvironmentBackupOptions   `tfsdk:"backup_options"`
	CoreCIDR            types.String                                        `tfsdk:"core_cidr"`
	Created             types.String                                        `tfsdk:"created"`
	DashboardURL        types.String                                        `tfsdk:"dashboard_url"`
	DatadogSettings     ClickhouseClusterResponseEnvironmentDatadogSettings `tfsdk:"datadog_settings"`
	Domain              types.String                                        `tfsdk:"domain"`
	ExternalDNS         types.String                                        `tfsdk:"external_dns"`
	ID                  types.String                                        `tfsdk:"id"`
	IDOwner             types.String                                        `tfsdk:"id_owner"`
	IsAnywhere          types.Bool                                          `tfsdk:"is_anywhere"`
	KubeAPIURL          types.String                                        `tfsdk:"kube_api_url"`
	KubeAuthOptions     ClickhouseClusterResponseEnvironmentKubeAuthOptions `tfsdk:"kube_auth_options"`
	KubeCheck           types.String                                        `tfsdk:"kube_check"`
	KubeCHOVersion      types.String                                        `tfsdk:"kube_cho_version"`
	KubeLBType          types.String                                        `tfsdk:"kube_lb_type"`
	KubeManagedPVs      types.Bool                                          `tfsdk:"kube_managed_p_vs"`
	KubeNamespace       types.String                                        `tfsdk:"kube_namespace"`
	KubeNamespaceManage types.Bool                                          `tfsdk:"kube_namespace_manage"`
	KubeProvider        types.String                                        `tfsdk:"kube_provider"`
	KubeStartupMode     types.String                                        `tfsdk:"kube_startup_mode"`
	KubeToken           types.String                                        `tfsdk:"kube_token"`
	ListenCheck         types.String                                        `tfsdk:"listen_check"`
	LogsStorage         ClickhouseClusterResponseEnvironmentLogsStorage     `tfsdk:"logs_storage"`
	Monitoring          types.Bool                                          `tfsdk:"monitoring"`
	MonitoringInfo      ClickhouseClusterResponseEnvironmentMonitoringInfo  `tfsdk:"monitoring_info"`
	MonitoringURL       types.String                                        `tfsdk:"monitoring_url"`
	Name                types.String                                        `tfsdk:"name"`
	Options             ClickhouseClusterResponseEnvironmentOptions         `tfsdk:"options"`
	Pass                types.String                                        `tfsdk:"pass"`
	ResourceLimits      ClickhouseClusterResponseEnvironmentResourceLimits  `tfsdk:"resource_limits"`
	SniProxyForCH       types.Bool                                          `tfsdk:"sni_proxy_for_ch"`
	SslCertificateARN   types.String                                        `tfsdk:"ssl_certificate_arn"`
	Status              types.String                                        `tfsdk:"status"`
	Type                types.String                                        `tfsdk:"type"`
	User                types.String                                        `tfsdk:"user"`
	VpcEndpoints        types.Bool                                          `tfsdk:"vpc_endpoints"`
}
