// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"altinity/internal/sdk/pkg/models/shared"
	"net/http"
)

type PostAPIIDEnvironmentClusterLaunchRequest struct {
	ClickhouseClusterRequestInput shared.ClickhouseClusterRequestInput `request:"mediaType=application/json"`
	IDEnvironment                 string                               `pathParam:"style=simple,explode=false,name=id_environment"`
}

// PostAPIIDEnvironmentClusterLaunch2XXApplicationJSON - Ok
type PostAPIIDEnvironmentClusterLaunch2XXApplicationJSON struct {
	Data *shared.ClickhouseClusterResponse `json:"data,omitempty"`
}

type PostAPIIDEnvironmentClusterLaunchResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Ok
	PostAPIIDEnvironmentClusterLaunch2XXApplicationJSONObject *PostAPIIDEnvironmentClusterLaunch2XXApplicationJSON
}
