// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type PostAPIIDEnvironmentClusterLaunchRequest struct {
	ClickhouseClusterRequestInput shared.ClickhouseClusterRequestInput `request:"mediaType=application/json"`
	IDEnvironment                 string                               `pathParam:"style=simple,explode=false,name=id_environment"`
}

type PostAPIIDEnvironmentClusterLaunch2XXApplicationJSONMetadata struct {
	Changed bool `json:"changed"`
}

// PostAPIIDEnvironmentClusterLaunch2XXApplicationJSON - Ok
type PostAPIIDEnvironmentClusterLaunch2XXApplicationJSON struct {
	Data     *shared.ClickhouseClusterResponse                            `json:"data,omitempty"`
	Metadata *PostAPIIDEnvironmentClusterLaunch2XXApplicationJSONMetadata `json:"metadata,omitempty"`
}

type PostAPIIDEnvironmentClusterLaunchResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Ok
	PostAPIIDEnvironmentClusterLaunch2XXApplicationJSONObject *PostAPIIDEnvironmentClusterLaunch2XXApplicationJSON
}
